### ISSUE TITLE
What is the Weaver workflow for unit testing with mock objects?

### ISSUE THREAD

**Issue by amleszk** [scribd/Weaver#106]
Hi @trupin I really like this tool, it removes a lot of the boiler plate involved with dependency injection and the compile time checking is a good design choice which many other projects will overlook. My question/feature request is around mock objects. 

Can Weaver generate mock objects?
Is there plans to build into Weaver a feature to generate mock objects?

Many times when using dependency injection a mock object is required for the unit test. In your Sample project it looks like the mock is being written by hand, which is boiler plate.

Thanks for making Weaver open source.

**Comment by trupin** [comment]
Hi @amleszk,

There's no plan to make Weaver support mock objects generation. It is a complex task which IMO would require a separate tool.

Writing templates with [Sourcery](https://github.com/krzysztofzablocki/Sourcery) could be a good start. Maybe even enough.
