### ISSUE TITLE
Feature Request: Support for @escaping closures as parameters

### ISSUE THREAD

**Issue by StephaneMagne** [scribd/Weaver#108]
When adding a parameter requirement via weaver, etc:

// weaver: progressHUDToggler <= ProgressHUDToggler

where ProgressHUDToggler is a typealias for a closure, the dependency container will not label the closure escaping and the compiler will complain if I attempt to retain it.

Request: Add syntax to optionally mark a closure as escaping.

**Comment by LorienMan** [comment]
Hello @StephaneMagne ! As Optional closures are implicitly escaped you can work-around this problem passing ``` ProgressHUDToggler? ``` instead of ```ProgressHUDToggler```

**Comment by trupin** [comment]
Fixed in #123
