### ISSUE TITLE
Feature Request: protocol polymorphism with the same variable name

### ISSUE THREAD

**Issue by StephaneMagne** [scribd/Weaver#113]
Effectively the problem is, if I have a concrete type backed by multiple protocols, I want to be able to inherit sub-definitions of that protocol down the tree.

In a tree [A] -- [B] -- [C]

If node A defines:
```
// weaver: userManager = UserManager <- UserStateProviding & UserStateManaging
// weaver: userManager.scope = .transient
// weaver: userManager.builder = UserManager.make
```

and node B defines:
```
// weaver: userManager <- UserStateProviding
```

and node C defines:
```
// weaver: userManager <- UserStateManaging
```

Then the compiler will complain that the types do not match.

**Comment by trupin** [comment]
Addressed in #121
