### ISSUE TITLE
weaver generated func instead of var when using parameter annotation

### ISSUE THREAD

**Issue by longthanhle91** [scribd/Weaver#117]
Hi, I'm currently running into this problem where weaver would generate `func` instead of `var` when using `.container` scope with parameter annotation

I first created a `Sample` class that takes in a string, so I pass it in using weaver parameter annotation

```
import Foundation

public protocol SampleProtocol {}

public final class SampleClass : SampleProtocol {
    private let dep: SampleClassDependencyResolver
    // weaver: host <= String
    
    init(injecting dep: SampleClassDependencyResolver) {
        self.dep = dep
    }
}
```

and in `AppDelegate`, I added these:
```
// weaver: sample = SampleClass <- SampleProtocol
// weaver: sample.scope = .container
// weaver: sample.builder = AppDelegate.make
```

here is the builder for `Sample` class
```
extension AppDelegate {
    static func make(_ dep: AppDelegateDependencyResolver) -> SampleProtocol {
        return SampleClass(host: "sample host")
    }
}
```

weaver generated this:
```
/// This file is generated by Weaver 0.12.3
/// DO NOT EDIT!
import UIKit
// MARK: - AppDelegate
protocol AppDelegateDependencyResolver {
    func sample(host: String) -> SampleProtocol
}
final class AppDelegateDependencyContainer: AppDelegateDependencyResolver {
    private var _sample: SampleProtocol?
    func sample(host: String) -> SampleProtocol {
        if let value = _sample { return value }
        let value = AppDelegate.make(self)
        _sample = value
        return value
    }
    init() {
        _ = sample(host: host)
    }
}
```

and the compiler complained that `host` is unresolved

In the sample from weaver git, I found a very similar implementation in `Weaver/Sample/API/Manager/MovieManager.swift` but weaver was able to generated the correct code.
Please let me know if I'm doing something wrong here. Many thanks

**Comment by trupin** [comment]
Hi @longthanhle91,

Dependencies taking parameters can't be declared with a `container` scope. This is because a `container` scope requires the dependency to be built upfront while a dependency declaring a parameter also needs its parameter up front. Thus, the dependency can't be built.

To fix your issue, you'd have to declare `SampleClass` with a container `transient`. By doing so, you'll be able to instantiate it by giving the host parameter at the call site.

**Comment by longthanhle91** [comment]
thanks a lot for the explanation, I was looking at the sample app and thought that it's possible, closing this now
