### ISSUE TITLE
Generic error after trying to reproduce tutorial

### ISSUE THREAD

**Issue by Luzo** [scribd/Weaver#124]
What did I do:

- Installed weaver via Homebrew (version 1.0.0 for Catalina)
- Added group named Generated
- Added Run script phase to my app target
`weaver swift --project-path $PROJECT_DIR/$PROJECT_NAME --main-output-path Generated --input-path "*.swift"`
- Runned a project and got run phase error:
`ShellOut encountered an error
Status code: 1
Message: “”
Output: “”
Let the injection begin.
Listing files…
Command PhaseScriptExecution failed with a nonzero exit code`

I am using Xcode 11.2.1 and Catalina 10.15.1

Any help is welcome. 

Thank you

**Comment by trupin** [comment]
Hi Luzo,

Thanks for filing this.

The tutorial you are following isn't up to date. I will be working on updating it this week.

Can you try running `weaver swift --project-path $PROJECT_DIR/$PROJECT_NAME --main-output-path Generated`? 

`--input-path` doesn't support wildcards anymore, and I think that's what breaks in your case.

**Comment by trupin** [comment]
I updated the tutorial repository (branch `part1`) in order to give you better idea of what changed --> https://github.com/trupin/WeaverTutorial/tree/part1

Hopefully, this will help unblock you in your progress until I update the tutorial.

**Comment by Luzo** [comment]
Upon few tries I ended up with `$PODS_ROOT/WeaverDI/weaver/bin/weaver swift --project-path $PROJECT_DIR/$PROJECT_NAME --output-path Generated` which seems to be working. Do not know why, but suggested `weaver swift --project-path $PROJECT_DIR/$PROJECT_NAME --main-output-path Generated` was not working first, but now it is working. Really do not understand why, maybe it still ran old script instead of new, not sure. Finaly I see my AppDelegate weaver file.

Anyways, I guess this is resolved. Sidenote: personally, I would chose cloning from https: 
`git clone https://github.com/trupin/WeaverTutorialPart1.git` instead of ssh.
