### ISSUE TITLE
DependencyResolver & DependencyResolverProxy

### ISSUE THREAD

**Issue by LorienMan** [scribd/Weaver#128]
Hello!

Just a suggestion. In case of same dependencies names (but different types) (usually in parameters) we should now use `*ResolverProxy` type instead of `*Resolver` type. As an author of new class I don't really want to try `*Resolver` and if it fails use `*ResolverProxy`. 

We can normalize both types with typealiases, eg now:
```
typealias ClassADependencyResolver = Dep1Resolver & Dep2Resolver

struct ClassBDependencyResolverProxy { ... }
```
and with single naming rule:
```
typealias InternalClassADependencyResolver = Dep1Resolver & Dep2Resolver

typealias ClassADependencyResolver = InternalClassADependencyResolver

struct InternalClassBDependencyResolverProxy { ... }

typealias ClassBDependencyResolver = InternalClassBDependencyResolverProxy
```
We can now use `ClassADependencyResolver` and `ClassBDependencyResolver` in both cases.

**Comment by trupin** [comment]
Hi @LorienMan,

That's a good idea and I can definitely see the value in doing such a thing.

I'll try to free some time to do that soon, unless you want to give it a try.
