### ISSUE TITLE
Fails to parse source code in folder names that contain a space

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#33]
Weaver can't read (parse) files in folders with a space separated name.

Example:
```
Foo
 - SomeBar/Bar.swift
 - Some Bar/Bar.swift
```

Output from command `weaver --output_path ./ 'find ./Foo -name '*.swift' | xargs'`:
```
Parsing...
<- './Foo/SomeBar/Bar.swift'
Could not read contents of `./Foo/Some`
Could not read contents of `Bar/Bar.swift`
.
.
.
```

⚠️ Workaround: Remove spaces from your folder names.

**Comment by trupin** [comment]
This is because `xargs` doesn't output paths terminated by `\0` by default. Adding the option `-0` solves this issue.

```bash
$ weaver --output_path ./ 'find ./Foo -name '*.swift' | xargs -0'
```

I updated the sample and the readme (#36)
