### ISSUE TITLE
Ambiguous reference to member 'register(_:scope:name:builder:)'

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#34]
Made a container and I got:

![image](https://user-images.githubusercontent.com/5576161/41303491-ac072df4-6e6d-11e8-9937-5cb59d0b4b2f.png)

I think it may have something to do with the [bug in Swift 4](https://bugs.swift.org/browse/SR-6108).
This was resolved in the Cleanse DI as [following](https://github.com/square/Cleanse/issues/67)

**Comment by trupin** [comment]
Hi @ferologics,

Thanks for reporting this. 

I'm surprised I haven't caught this before. It might be an isolated bug on swift 4.0+. Which version of swift are you using? `4.0.+` or `4.1.+`?

Also, could you send me the code generated for `LocationManager.makeLocationManager(injection:)`?

**Comment by ferologics** [comment]
I'm using Swift `4.0` ATM.
I have reproduced same behaviour on Swift `4.2`.

[Generated code for LocationManager](https://github.com/scribd/Weaver/files/2095431/Weaver.LocationManager.swift.zip)

**Comment by trupin** [comment]
Thanks! I'll look into this asap.

**Comment by trupin** [comment]
I haven't been able to reproduce with neither `4.0.3` nor `4.1.2`. I haven't tried with swift `4.2.0` yet, but I'm downloading Xcode 10 right now in order to test.

I wonder if the issue you have could be due to an edge case of the library rather than a swift bug. Could you please send me a copy of a project reproducing the error? It would be a lot easier to see what's wrong, and hopefully I'll be able to get the same error on my machine.

**Comment by trupin** [comment]
Just tried with swift `4.2.0` and can't reproduce the issue either.

**Comment by ferologics** [comment]
I can't send you the project but I will try to reproduce in another one and send that over.

**Comment by ferologics** [comment]
Hey @trupin I managed to reproduce the error in the separate project 👉 [Test.zip](https://github.com/scribd/Weaver/files/2096792/Test.zip)

**Comment by ferologics** [comment]
Oh, and another observation 👉 omitting the `// weaver: locationAPI <- APIProtocol` dependency declaration in `LocationManager` eliminates the error.

**Comment by ferologics** [comment]
Closing the issue since this turned out not to be an issue of Weaver but of my apparently intermittent dyslexia. I overlooked the missing conformation to the protocol that I defined to be required by the container 😅

**Comment by trupin** [comment]
Oh ok, the `LocationManager` wasn't inheriting from `LocationManaging`. The compilation error doesn't show the problem very clearly. I'll add a "known issues" file to the documentation with this first one.

**Comment by ferologics** [comment]
Yep, it was quite a pain to find, having an error for this would be very helpful for early adopters who may be confused by the annotation syntax.

Talking about error handling, I noticed when I get the `invalid dependency graph starting with` error, it does not show me the warning suggestion in Xcode.

I had to run Weaver from command line to get the log that would point me in the right direction.
```
error: Detected invalid dependency graph starting with 'urlSession: URLSession'. Dependency cannot be resolved.
warning: Could not find the dependency 'urlSession' in 'LocationDataSource'. You may want to register it here to solve this issue.
```

**Comment by trupin** [comment]
I added a `KnownIssues.md` file in the `Documentation` directory --> 9b63c74300582034cb736fa4a941650b7ca8499c

**Comment by trupin** [comment]
For the `warning` not showing correctly, I tried and it works pretty well on the sample project on both Xcode 10 & 9.4. 

Could you open a ticket with all the details and reproduction steps please? This warning is indeed important, and I would like to make sure end users are able to see it.
