### ISSUE TITLE
Protocol dependency specialisation typos could show error

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#39]
Would be a nice to have if Weaver produced an error for the protocol typo.
`LocationSourcable` -> `LocationSourceable`

<img width="790" alt="image" src="https://user-images.githubusercontent.com/5576161/41459977-73d40658-708b-11e8-9479-4457928a0ace.png">

<img width="987" alt="image" src="https://user-images.githubusercontent.com/5576161/41459950-5f2405f0-708b-11e8-84e5-840e25e62369.png">

**Comment by trupin** [comment]
Sorry @ferologics, just realized I haven't answered on this ticket. I want to work on improving error handling soon so I think I'll try to make this ticket a part of it. It'll probably come in `v0.12.0`.

**Comment by trupin** [comment]
FYI @ferologics, this is being addressed by #121 which will get merged and released soon.

**Comment by trupin** [comment]
Addressed in #121
