### ISSUE TITLE
How to distribute a framework without the Weaver dependency?

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#41]
I can create an umbrella framework and include Weaver inside but that is not a recommended pattern. 

Is there a way to include the weaver sources instead of `import Weaver` in release targets?

**Comment by trupin** [comment]
Hi @ferologics,

I'm not sure to understand what you're trying to do exactly.

If you're trying to use weaver in your framework without any need to import it, then the only way I can think of would be to import weaver's sources manually into your project. Maybe with a git submodule? 

I don't see why having weaver as a dependency of your framework would be problematic though.
