### ISSUE TITLE
Does not support cocoapod

### ISSUE THREAD

**Issue by ZZHHAANNGG** [scribd/Weaver#42]
pod search WeaverDI cannot find any pod

**Comment by trupin** [comment]
Hi @ZZHHAANNGG,

WeaverDI is referenced correctly on [cocapods website](https://cocoapods.org/pods/WeaverDI) and a `pod search WeaverDI` outputs correctly on my machine:

```
-> WeaverDI (0.9.9)
   Declarative, easy-to-use and safe Dependency Injection framework for Swift (iOS/macOS/Linux)
   pod 'WeaverDI', '~> 0.9.9'
   - Homepage: https://github.com/scribd/Weaver
   - Source:   https://github.com/scribd/Weaver.git
   - Versions: 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5 [master repo]
```

Have you tried to do a `pod repo update` before searching?

**Comment by ZZHHAANNGG** [comment]
I just tried, but still cannot find it

`
pod search WeaverDI 
[!] Unable to find a pod with name, author, summary, or description matching `WeaverDI`

pod repo update
Updating spec repo `master`
  $ /usr/bin/git -C /Users/zhb/.cocoapods/repos/master fetch origin --progress
  remote: Counting objects: 9536, done.
  remote: Compressing objects: 100% (155/155), done.
  remote: Total 9536 (delta 3852), reused 3805 (delta 3805), pack-reused 5569
  Receiving objects: 100% (9536/9536), 1.06 MiB | 269.00 KiB/s, done.
  Resolving deltas: 100% (6372/6372), completed with 1445 local objects.
  From https://github.com/CocoaPods/Specs
     2c880fa4439..0abc6b1fc67  master     -> origin/master
  $ /usr/bin/git -C /Users/zhb/.cocoapods/repos/master rev-parse --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/zhb/.cocoapods/repos/master reset --hard origin/master
  HEAD is now at 0abc6b1fc67 [Add] MHInteractiveClock 0.0.7

CocoaPods 1.5.3 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.3

pod search WeaverDI
[!] Unable to find a pod with name, author, summary, or description matching `WeaverDI`
`

**Comment by trupin** [comment]
It looks like this happens when you local cache is out of date.

This is an issue talking about this problem: https://github.com/CocoaPods/CocoaPods/issues/6221

Could you try to do `rm -rf ~/Library/Caches/Cocoapods` and try to search again?

**Comment by ZZHHAANNGG** [comment]
It works! Thanks
