### ISSUE TITLE
Need some examples using Weaver, RxSwift in MVVM

### ISSUE THREAD

**Issue by ZZHHAANNGG** [scribd/Weaver#43]
Need some examples of how Weaver can benefit the project is written in RxSwift MVVM

**Comment by trupin** [comment]
Hi @ZZHHAANNGG,

This is something I would love to do, but I unfortunately don't have time for this right now.

I'm putting this on the backlog for this project.

If you feel comfortable writing one, don't hesitate to do so and ask me for help if needed.
