### ISSUE TITLE
Documentation for generated convenience init with tokens

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#44]
How would I document the [public convenience init](https://github.com/scribd/Weaver/blob/master/Sample/API/Generated/Weaver.MovieManager.swift#L76-L78
)?

⚠️ Workaround: Disable weaver script build step and document the function in generated code

**Comment by ferologics** [comment]
Alternatively a more convenient workaround is to conform to protocol which is documenting the generated convenience init as such:

```swift
protocol EstimoteIndoorProtocol {
  /// Authorizing init.
  ///
  /// - Parameters:
  ///   - appId: Your app identifier.
  ///   - appToken: Your app token.
  init(appId: AppId, appToken: AppToken)
}
```

**Comment by trupin** [comment]
Hi @ferologics,

That's an interesting question. I think your alternative workaround is the right approach for this.

We could also add a configuration variable to deactivate the generation of the `public convenience init` and let the developer write it himself, but it might be a bit confusing to add this to weaver's API for this purpose only.

Another approach, which would need more work would be to make weaver automatically extract the comments from the class initializer like so:

```swift
public final class Foo: FooProtocol {
  private let dependencies: FooDependencyResolver
  
  // weaver: appId <= AppId
  // weaver: appToken <= AppToken
  
  /// Authorizing init.
  ///
  /// - Parameters:
  ///   - appId: Your app identifier.
  ///   - appToken: Your app token.
  required init(injecting dependencies: FooDependencyResolver) {
    ...
  }
}
``` 

would generate:

```swift
extension Foo {
  /// Authorizing init.
  ///
  /// - Parameters:
  ///   - appId: Your app identifier.
  ///   - appToken: Your app token.
  public convenience init(appId: AppId, appToken: AppToken) {
    ...
  }
}
```

- What do you think?

**Comment by ferologics** [comment]
Those are good suggestions, but I think it's too much work for a mediocre result, b/c no autogenerated comments for the init from params, misplacement of the actual documentation etc.

Let's either stick with the protocol workaround for the time being (and document it for future references), or force the developer to implement the init on her own.

The latter is a good option, but it would insinuate the removal of the parameter annotation.

On the side note: I think Weaver's parameters are a tad bit unclear. Maybe adding an example of the generated convenience init would further clarify the API usage.

**Comment by trupin** [comment]
Closing this ticket since the workaround you described seems to be enough for now. Feel free to reopen it if needed.
