### ISSUE TITLE
Error: Compiler is unable to type-check this expression

### ISSUE THREAD

**Issue by ferologics** [scribd/Weaver#57]
The Swift compiler is a simpleton when it comes to installing Weaver via Homebrew.

Log:
```sh
rohlik@Macs-MacBook-Pro ~/E/EstimoteIndoor> brew tap trupin/homebrew-core                                                                                                                                                                                  rohlik@Macs-MacBook-Pro ~/E/EstimoteIndoor> brew install weaver
Updating Homebrew...
==> Installing weaver from trupin/core
==> Downloading https://github.com/scribd/Weaver/archive/0.10.0.tar.gz
==> Downloading from https://codeload.github.com/scribd/Weaver/tar.gz/0.10.0
######################################################################## 100.0%
==> make install PREFIX=/usr/local/Cellar/weaver/0.10.0
Last 15 lines from /Users/rohlik/Library/Logs/Homebrew/weaver/01.make:
                                                                ^
/private/tmp/weaver-20180803-78964-7y3j8w/Weaver-0.10.0/.build/checkouts/Stencil.git-9192458680909420027/Sources/Variable.swift:63:39: warning: 'characters' is deprecated: Please use String or Substring directly
      return String(variable[variable.characters.index(after: variable.startIndex) ..< variable.characters.index(before: variable.endIndex)])
                                      ^
/private/tmp/weaver-20180803-78964-7y3j8w/Weaver-0.10.0/.build/checkouts/Stencil.git-9192458680909420027/Sources/Variable.swift:63:97: warning: 'characters' is deprecated: Please use String or Substring directly
      return String(variable[variable.characters.index(after: variable.startIndex) ..< variable.characters.index(before: variable.endIndex)])
                                                                                                ^
Compile Swift Module 'StencilSwiftKit' (11 sources)
/private/tmp/weaver-20180803-78964-7y3j8w/Weaver-0.10.0/.build/checkouts/StencilSwiftKit.git-7192738263873710759/Sources/SwiftIdentifier.swift:16:55: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
private let headRanges: [CountableClosedRange<Int>] = [
                                                      ^
error: terminated(1): /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /private/tmp/weaver-20180803-78964-7y3j8w/Weaver-0.10.0/.build/release.yaml main output:


make: *** [build] Error 1
```

**Comment by ferologics** [comment]
This is an issue with `StencilSwiftKit`. It was resolved in https://github.com/SwiftGen/StencilSwiftKit/issues/92 and released in version 2.5.0.

**Comment by trupin** [comment]
I updated StencilSwiftKit in a PR (#58). Let me know if that works for you.

**Comment by ferologics** [comment]
@trupin I was wrong. They did not include it in the release (4 days ago) but the change is merged on master from 13 days earlier. AFAIK Swift packages depend on release tags / you'll have to wait for the next release to include the fix. 

You know of a possible workaround in the meantime? 

I'm not able to build the project with Carthage [see carthage-xcodebuild.1v2rIX.log](https://github.com/scribd/Weaver/files/2258113/carthage-xcodebuild.1v2rIX.log)
```
> carthage update
*** Fetching Weaver
*** Checking out Weaver at "f013cf6498bdf1ff4d29653e7ffd125d8ca3cd7f"
*** xcodebuild output can be found in /var/folders/0q/mp3pts2j5nv548s4ss459g380000gn/T/carthage-xcodebuild.1v2rIX.log
*** Building scheme "WeaverCodeGen" in Weaver.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/rohlik/Project/Carthage/Checkouts/Weaver/Weaver.xcodeproj -scheme WeaverCodeGen -configuration Release -derivedDataPath /Users/rohlik/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10L213o/Weaver/f013cf6498bdf1ff4d29653e7ffd125d8ca3cd7f ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/0q/mp3pts2j5nv548s4ss459g380000gn/T/Weaver SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/rohlik/Project/Carthage/Checkouts/Weaver)
```

**Comment by trupin** [comment]
@ferologics, mmm that's a bummer. A workaround would be to install weaver's binary directly as explained in the [readme](https://github.com/scribd/Weaver#binary-form)

For the Carthage issue, this is normal that weaver won't build with it anymore. I removed the runtime part of Weaver, meaning it is now only composed of a command line tool. See the [migration guide](https://github.com/scribd/Weaver/blob/master/Documentation/Migration_from_0.9.%2B_to_0.10.%2B.md) for more details.

**Comment by ferologics** [comment]
Oh, cool. So then how does one know Weaver is a dependency in the project? That also means no “import WeaverDI” in sources, right?

**Comment by trupin** [comment]
No one can know that Weaver is a dependency of a project unless by reading the sources and looking at the generated files

And yes that's exactly what that means. I actually entirely removed the WeaverDI framework, which is why it doesn't compile with Carthage anymore.

**Comment by ferologics** [comment]
Good decision, now all is clear and simpler in Weaver.

As far as the issue goes, I am able to install by modifying the sources of `StencilSwiftKit`. In particular the required change was - as referenced by above PR - in the `SwiftIdentifier.swift` file. The modified version is attached.

### ⚠️Workaround
Replace the `SwiftIdentifier.swift` file in the locally checked out StencilSwiftKit package for the attached file with applied hot-fix. 

#### Auxilary
- example path to the file 👉`Weaver/.build/checkouts/StencilSwiftKit.git-1491519766941871081/Sources/SwiftIdentifier.swift`

#### Attachments
- fixed [SwiftIdentifier.swift.zip](https://github.com/scribd/Weaver/files/2259798/SwiftIdentifier.swift.zip)

**Comment by trupin** [comment]
@ferologics you're workaround looks good. Unless you want to compile master to have the latest changes, you can install weaver with the [binary](
https://github.com/scribd/Weaver/releases/download/0.10.0/weaver-0.10.0.zip) directly though. It's probably easier.

**Comment by trupin** [comment]
@ferologics, now that Weaver has been merged into the core repo of Homebrew, you can get rid of the tap `trupin/homebrew-core` and reinstall Weaver. This will use the bottle system of Homebrew and install the binaries directly. Thus, this issue shouldn't happen anymore.

I'm closing this, but feel free to reopen it if needed.
