### ISSUE TITLE
ObjC-compatible containers with no injected dependencies missing an override keyword on init

### ISSUE THREAD

**Issue by bdorfman** [scribd/Weaver#74]
If you create an objective-c compatible container and it has no injected dependencies (e.g. its the root container), the generated Container class will have `init()` instead of `init(injecting dependencies:)`. The compiler complains that this `init()` needs to have an `override` keyword on it (since it is inheriting from `NSObject`).

**Comment by trupin** [comment]
Hey @bdorfman,

Thanks for reporting this. That's a scenario I didn't think about. I'll come up with a fix as soon as possible.

**Comment by trupin** [comment]
Fixed by #75
