### ISSUE TITLE
Why no CocoaPods support?

### ISSUE THREAD

**Issue by indieSoftware** [scribd/Weaver#91]
Regarding the history weaver was once available via CocoaPods up until version 0.9, but dropped it then. Why?

Homebrew support might be nice, but it's more suitable for single developers than for teams. In teams everybody has to be on the same page. Therefore I always add all dependencies of a project into source control. That way when checking out the latest branch we can be sure everybody has exactly the same setup and everything is consistent. At plus it's possible to use different versions for different projects. With Homebrew this isn't possible at least not so easy.

Well, the second option, installing weaver manually is even worse. When trying to use it weaver says the stencil file couldn't be found at /usr/local/share/weaver/Resources. So I'm forced to copy it manually and have no chance to put it into source control for a specific project again. At plus I don't get automatically the newest version of weaver because I have to look for it manually.

That's why dependency resolvers like CocoaPods & co are good for. So I really miss the pod support here. Without it I won't use weaver in my tooling pipeline. It's simply not practicable. That's sad, because weaver sounds really cool and better than Swinject.

Btw, the readme documentation seems to be outdated, because `weaver swift` returns `Unknown command`.

**Comment by trupin** [comment]
Hi @indieSoftware,

Thanks for your feedback.

> Regarding the history weaver was once available via CocoaPods up until version 0.9, but dropped it then. Why?
Cocoapods was only supported to install the Weaver's runtime library which became obsolete after v0.9. This is why there's no mention of Cocoapods anymore.

I didn't think that Cocoapods could also be used to install command line tools, but apparently it can (e.g. [SwiftLint](https://github.com/realm/SwiftLint/blob/master/SwiftLint.podspec)). I'll file this right now and try to get it in the next release which I plan on doing very soon.

> Well, the second option, installing weaver manually is even worse. When trying to use it weaver says the stencil file couldn't be found at /usr/local/share/weaver/Resources.
This is a pretty unfortunate bug which I'll file and solve asap.

> Btw, the readme documentation seems to be outdated, because `weaver swift` returns `Unknown command`.
The readme is actually too up to date. This is the documentation of the master branch, on which I renamed the command `generate` to `swift`. The breaking changes of that new version will be documented soon, and master's readme will be in sync as soon as I push the next release.

**Comment by trupin** [comment]
Just filed two tickets:
- #93 : Cocoapods support.
- #92 : Archive installation bug.

**Comment by indieSoftware** [comment]
Thank's for the answers.

CocoaPods is useful for pipeline tools, like SwiftLint, SwiftFormat and R-swift. Weaver seems to fit into this category very well, therefore I really appreciate #93.
